version: '3.6'
services:
  php:
    build:
      args:
        - ENABLE_DEBUGGER=1
        - XDEBUG_PORT=9005
        - XDEBUG_IDE=PHPSTORM
    networks:
      jagaad_dev:
        aliases:
            - jagaad_witcher_dev

  rabbitmq:
    networks:
      - jagaad_dev

  elasticsearch:
    networks:
      - jagaad_dev

  web:
    networks:
      - jagaad_dev
  mysql:
    networks:
      - jagaad_dev
volumes:
  mysql: null
networks:
  jagaad_dev:
    name: jagaad
