api_platform:
    title: 'Jagaad Witcher API'
    version: '0.1'
    show_webby: true
    name_converter: ~
    allow_plain_identifiers: true
    enable_swagger: true
    enable_swagger_ui: true
    enable_profiler: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResource'

    elasticsearch:
        hosts: [ '%env(normalize_url:ELASTICSEARCH_URL)%' ]
        mapping:
            Jagaad\WitcherApi\ApiResource\History:
                index: history

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    eager_loading: false
