security:
    access_decision_manager:
        strategy: unanimous

    providers:
        users_in_memory: { memory: null }
        user_provider_bundle_provider:
            id: jagaad.user_provider.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        jagaad_user_provider:
            entry_point: Jagaad\WitcherApi\Security\AuthenticationEntryPoint
            anonymous: true
            provider: user_provider_bundle_provider
            form_login:
                login_path: app_login
                check_path: jagaad.user_provider.authentication.callback
            logout:
                path: jagaad.user_provider.authentication.logout
            guard:
                authenticators:
                    - jagaad.user_provider.authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_user-provider/authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/webhooks, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
