<?php

declare(strict_types=1);

namespace Jagaad\WitcherApi\Enum;

final class ContextGroup
{
    public const GROUP_STATUS_WRITE = 'GROUP_STATUS_WRITE';
    public const GROUP_STATUS_READ = 'GROUP_STATUS_READ';
    public const PROJECT_TRACKER_TASK_TYPE_READ = 'PROJECT_TRACKER_TASK_TYPE_READ';
    public const PROJECT_TRACKER_TASK_TYPE_WRITE = 'PROJECT_TRACKER_TASK_TYPE_WRITE';

    public const GROUP_GITLAB_PROJECT_READ = 'GROUP_GITLAB_PROJECT_READ';

    public const GROUP_TECHNOLOGY_WRITE = 'GROUP_TECHNOLOGY_WRITE';
    public const GROUP_TECHNOLOGY_READ = 'GROUP_TECHNOLOGY_READ';

    public const GROUP_CLIENT_READ = 'GROUP_CLIENT_READ';
    public const GROUP_CLIENT_WRITE = 'GROUP_CLIENT_WRITE';
    public const GROUP_GENERIC_TRAIT_WRITE = 'GROUP_GENERIC_TRAIT_WRITE';
    public const GROUP_GENERIC_TRAIT_READ = 'GROUP_GENERIC_TRAIT_READ';

    public const GROUP_WEEKLY_TASK_READ = 'GROUP_WEEKLY_TASK_READ';

    public const GROUP_PROJECT_READ = 'GROUP_PROJECT_READ';
    public const GROUP_PROJECT_WRITE = 'GROUP_PROJECT_WRITE';
    public const GROUP_PRIORITY_READ = 'GROUP_PRIORITY_READ';
    public const GROUP_PRIORITY_WRITE = 'GROUP_PRIORITY_WRITE';

    public const GROUP_WITCHER_USER_READ = 'GROUP_WITCHER_USER_READ';
    public const GROUP_WITCHER_USER_WRITE = 'GROUP_WITCHER_USER_WRITE';

    public const GROUP_ACTIVITY_READ = 'GROUP_ACTIVITY_READ';
    public const GROUP_ACTIVITY_WRITE = 'GROUP_ACTIVITY_WRITE';

    public const GROUP_TASK_READ = 'GROUP_TASK_READ';
    public const GROUP_TASK_WRITE = 'GROUP_TASK_WRITE';
    public const GROUP_TEAM_READ = 'GROUP_TEAM_READ';
    public const GROUP_TEAM_WRITE = 'GROUP_TEAM_WRITE';

    public const GROUP_GIT_PROJECT_WRITE = 'GROUP_GIT_PROJECT_WRITE';

    public const GROUP_GIT_COMMIT_READ = 'GROUP_GIT_COMMIT_READ';
    public const GROUP_GIT_COMMIT_WRITE = 'GROUP_GIT_COMMIT_WRITE';
    public const GROUP_PROJECT_EVENT_READ = 'GROUP_PROJECT_EVENT_READ';
    public const GROUP_HISTORY_READ = 'HISTORY_READ';

    public const GROUP_COMPANY_POSITION_READ = 'GROUP_COMPANY_POSITION_READ';
    public const GROUP_COMPANY_POSITION_WRITE = 'GROUP_COMPANY_POSITION_WRITE';

    public const GROUP_DEPARTMENT_READ = 'GROUP_DEPARTMENT_READ';
    public const GROUP_DEPARTMENT_WRITE = 'GROUP_DEPARTMENT_WRITE';

    public const GROUP_GENERAL_DICTIONARY_READ = 'GROUP_GENERAL_DICTIONARY_READ';
    public const GROUP_GENERAL_DICTIONARY_WRITE = 'GROUP_GENERAL_DICTIONARY_WRITE';

    public const GROUP_TASK_COMMENT_READ = 'GROUP_TASK_COMMENT_READ';
    public const GROUP_TASK_COMMENT_WRITE = 'GROUP_TASK_COMMENT_WRITE';
    public const GROUP_LABEL_WRITE = 'GROUP_LABEL_WRITE';
    public const GROUP_ALLOW_MODIFY = 'GROUP_ALLOW_MODIFY';

    public const GROUP_ROLE_READ = 'GROUP_ROLE_READ';
    public const GROUP_ROLE_WRITE = 'GROUP_ROLE_WRITE';

    public const GROUP_PERMISSION_READ = 'GROUP_PERMISSION_READ';

    public const GROUP_SPRINT_READ = 'GROUP_SPRINT_READ';
    public const GROUP_SPRINT_WRITE = 'GROUP_SPRINT_WRITE';

    public const GROUP_PROJECT_TYPE_WRITE = 'GROUP_PROJECT_TYPE_WRITE';
}
