<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211110182607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Created name table because renamed tablename, columnname and indexname as per ticket WITCHER-161';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, task INT NOT NULL, owner INT NOT NULL, activity_type INT NOT NULL, duration INT NOT NULL, comment VARCHAR(400) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_activity_active (active), INDEX IDX_activity_createdAt (dtmCreatedAt), INDEX IDX_activity_duration (duration), INDEX IDX_activity_updatedAt (updated_at), INDEX IDX_activity_deletedAt (deleted_at), INDEX IDX_activity_activityType (activity_type), INDEX IDX_activity_task (task), INDEX IDX_activity_owner (owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE business_branch (id INT AUTO_INCREMENT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_business_branch_displayOrder (display_order), INDEX IDX_business_branch_createdAt (dtmCreatedAt), INDEX IDX_business_branch_active (active), INDEX IDX_business_branch_deletedAt (deleted_at), UNIQUE INDEX UK_business_branch_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, country INT DEFAULT NULL, industry INT DEFAULT NULL, currency INT DEFAULT NULL, name VARCHAR(50) NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_client_active (active), INDEX IDX_client_createdAt (dtmCreatedAt), INDEX IDX_client_deletedAt (deleted_at), INDEX IDX_client_country (country), INDEX IDX_client_industry (industry), INDEX IDX_client_currency (currency), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_country_displayOrder (display_order), INDEX IDX_country_active (active), INDEX IDX_country_createdAt (dtmCreatedAt), INDEX IDX_country_deletedAt (deleted_at), UNIQUE INDEX UK_country_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_currency_displayOrder (display_order), INDEX IDX_currency_createdAt (dtmCreatedAt), INDEX IDX_currency_active (active), INDEX IDX_currency_deletedAt (deleted_at), UNIQUE INDEX UK_currency_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE git_branch (id INT AUTO_INCREMENT NOT NULL, git_project INT DEFAULT NULL, task INT DEFAULT NULL, branch_name VARCHAR(100) NOT NULL, web_url VARCHAR(200) NOT NULL, merged TINYINT(1) DEFAULT \'0\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, INDEX IDX_git_branch_gitProject (git_project), INDEX IDX_git_branch_task (task), UNIQUE INDEX UK_git_branch_branchName_gitProject (branch_name, git_project), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE industry (id INT AUTO_INCREMENT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_industry_displayOrder (display_order), INDEX IDX_industry_createdAt (dtmCreatedAt), INDEX IDX_industry_active (active), INDEX IDX_industry_deletedAt (deleted_at), UNIQUE INDEX UK_industry_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE priority (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(200) DEFAULT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_priority_displayOrder (display_order), INDEX IDX_priority_createdAt (dtmCreatedAt), INDEX IDX_priority_active (active), INDEX IDX_priority_deletedAt (deleted_at), UNIQUE INDEX UK_priority_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE project_sale_type (id INT AUTO_INCREMENT NOT NULL, business_branch INT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_project_sale_type_displayOrder (display_order), INDEX IDX_project_sale_type_createdAt (dtmCreatedAt), INDEX IDX_project_sale_type_active (active), INDEX IDX_project_sale_type_deletedAt (deleted_at), INDEX IDX_project_sale_type_businessBranch (business_branch), UNIQUE INDEX UK_project_sale_type_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE status (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(200) NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_status_displayOrder (display_order), INDEX IDX_status_createdAt (dtmCreatedAt), INDEX IDX_status_active (active), INDEX IDX_status_deletedAt (deleted_at), UNIQUE INDEX UK_status_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE task (id INT AUTO_INCREMENT NOT NULL, witcher_project INT NOT NULL, assignee INT DEFAULT NULL, reporter INT DEFAULT NULL, creator INT DEFAULT NULL, status INT NOT NULL, priority INT DEFAULT NULL, witcher_project_tracker_task_type INT NOT NULL, parent_task INT DEFAULT NULL, jira_link VARCHAR(200) DEFAULT NULL, description VARCHAR(2000) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_task_displayOrder (display_order), INDEX IDX_task_createdAt (dtmCreatedAt), INDEX IDX_task_deletedAt (deleted_at), INDEX IDX_task_witcherProjectTrackerTaskType (witcher_project_tracker_task_type), INDEX IDX_task_witcherProject (witcher_project), INDEX IDX_task_assignee (assignee), INDEX IDX_task_reporter (reporter), INDEX IDX_task_creator (creator), INDEX IDX_task_status (status), INDEX IDX_task_priority (priority), INDEX IDX_task_parentTask (parent_task), UNIQUE INDEX UK_task_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE technology (id INT AUTO_INCREMENT NOT NULL, friendly_name VARCHAR(30) NOT NULL, handle VARCHAR(30) NOT NULL, display_order INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_technology_displayOrder (display_order), INDEX IDX_technology_createdAt (dtmCreatedAt), INDEX IDX_technology_active (active), INDEX IDX_technology_deletedAt (deleted_at), UNIQUE INDEX UK_technology_handle (handle), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE witcher_project (id INT AUTO_INCREMENT NOT NULL, business_branch INT DEFAULT NULL, witcher_user INT DEFAULT NULL, client INT DEFAULT NULL, sale_type INT DEFAULT NULL, tracker_project INT DEFAULT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(400) DEFAULT NULL, is_billable TINYINT(1) DEFAULT \'1\' NOT NULL, confluence_link VARCHAR(150) DEFAULT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_witcher_project_deletedAt (deleted_at), INDEX IDX_witcher_project_businessBranch (business_branch), INDEX IDX_witcher_project_owner (witcher_user), INDEX IDX_witcher_project_client (client), INDEX IDX_witcher_project_projectSaleType (sale_type), UNIQUE INDEX UK_witcher_project_trackerProject (tracker_project), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE witcher_user (id INT AUTO_INCREMENT NOT NULL, company_position INT NOT NULL, supervisor INT DEFAULT NULL, user_id INT NOT NULL, witcher_roles JSON NOT NULL, git_lab_user_id INT NOT NULL, jira_account VARCHAR(128) NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_witcher_user_active (active), INDEX IDX_witcher_user_createdAt (dtmCreatedAt), INDEX IDX_witcher_user_deletedAt (deleted_at), INDEX IDX_witcher_user_companyPosition (company_position), UNIQUE INDEX UK_witcher_user_gitLabUserId (git_lab_user_id), UNIQUE INDEX UK_witcher_user_supervisor (supervisor), UNIQUE INDEX UK_witcher_user_jiraAccount (jira_account), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tblActivity (activity_type INT NOT NULL, intId INT AUTO_INCREMENT NOT NULL, intDuration INT NOT NULL, strComment VARCHAR(400) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dtmUpdatedAt DATETIME DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, intTaskId INT NOT NULL, intOwnerId INT NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_7A198205AEAE0B42 (intTaskId), INDEX IDX_7A198205C04C9957 (intOwnerId), INDEX IDX_tblActivity_activity_type (activity_type), INDEX IDX_tblActivity_bolActive (bolActive), INDEX IDX_tblActivity_deletedAt (deleted_at), INDEX IDX_tblActivity_dtmCreatedAt (dtmCreatedAt), INDEX IDX_tblActivity_dtmUpdatedAt (dtmUpdatedAt), INDEX IDX_tblActivity_intDuration (intDuration), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE tblClient (intId INT AUTO_INCREMENT NOT NULL, strName VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, intCountryId INT DEFAULT NULL, intIndustryId INT DEFAULT NULL, intCurrencyId INT DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_E4B4A7E0345D687F (intCurrencyId), INDEX IDX_E4B4A7E065E37C67 (intIndustryId), INDEX IDX_E4B4A7E0AC743893 (intCountryId), INDEX IDX_tblClient_bolActive (bolActive), INDEX IDX_tblClient_deletedAt (deleted_at), INDEX IDX_tblClient_dtmCreatedAt (dtmCreatedAt), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE tblGitBranch (intId INT AUTO_INCREMENT NOT NULL, strBranchName VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strWebUrl VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, bolMerged TINYINT(1) DEFAULT \'0\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, intGitProjectId INT DEFAULT NULL, intTaskId INT DEFAULT NULL, INDEX IDX_tblGitBranch_intGitProjectId (intGitProjectId), INDEX IDX_tblGitBranch_intTaskId (intTaskId), UNIQUE INDEX UK_tblGitBranch_strBranchName_intGitProjectId (strBranchName, intGitProjectId), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE tblTask (witcher_project_tracker_task_type INT NOT NULL, strJiraLink VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, strDescription VARCHAR(2000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, intWitcherProjectId INT NOT NULL, intAssigneeId INT DEFAULT NULL, intReporterId INT DEFAULT NULL, intStatusId INT NOT NULL, intPriorityId INT DEFAULT NULL, intParentTaskId INT DEFAULT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, intCreatorId INT DEFAULT NULL, dtmUpdatedAt DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_4FBDB45C2F9A3779 (intParentTaskId), INDEX IDX_4FBDB45C3281966B (intWitcherProjectId), INDEX IDX_4FBDB45C4F39F20C (intStatusId), INDEX IDX_4FBDB45C736452D1 (intCreatorId), INDEX IDX_4FBDB45C9603796 (intReporterId), INDEX IDX_4FBDB45C975EADA1 (intAssigneeId), INDEX IDX_4FBDB45CDA406E3B (intPriorityId), INDEX IDX_tblTask_deletedAt (deleted_at), INDEX IDX_tblTask_dtmCreatedAt (dtmCreatedAt), INDEX IDX_tblTask_intDisplayOrder (intDisplayOrder), INDEX IDX_tblTask_witcher_project_tracker_task_type (witcher_project_tracker_task_type), UNIQUE INDEX UK_tblTask_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE tblWitcherProject (tracker_project INT DEFAULT NULL, intId INT AUTO_INCREMENT NOT NULL, strName VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strDescription VARCHAR(400) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, bolIsBillable TINYINT(1) DEFAULT \'1\' NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, dtmCreatedAt DATETIME NOT NULL, intBusinessBranchId INT DEFAULT NULL, intWictherUserId INT DEFAULT NULL, intClientId INT DEFAULT NULL, intSaleTypeId INT DEFAULT NULL, strConfluenceLink VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL, INDEX IDX_57087355437EBCA (intClientId), INDEX IDX_570873563E1464C (intSaleTypeId), INDEX IDX_57087357506BE97 (intWictherUserId), INDEX IDX_5708735C096CAA3 (intBusinessBranchId), INDEX IDX_tblWitcherProject_deletedAt (deleted_at), UNIQUE INDEX UK_tblWitcherProject_tracker_project (tracker_project), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE tblWitcherUser (company_position INT NOT NULL, supervisor INT DEFAULT NULL, intId INT AUTO_INCREMENT NOT NULL, intUserId INT NOT NULL, jsonWitcherRoles JSON CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, intGitlabUserId INT NOT NULL, strJiraAccount VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL, INDEX IDX_tblWitcherUser_bolActive (bolActive), INDEX IDX_tblWitcherUser_company_position (company_position), INDEX IDX_tblWitcherUser_deletedAt (deleted_at), INDEX IDX_tblWitcherUser_dtmCreatedAt (dtmCreatedAt), UNIQUE INDEX UK_tblWitcher_supervisor (supervisor), UNIQUE INDEX UK_tblWitcherUser_intGitlabUserId (intGitlabUserId), UNIQUE INDEX UNIQ_8144503616F73C1 (strJiraAccount), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublBusinessBranch (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublBusinessBranch_bolActive (bolActive), INDEX IDX_ublBusinessBranch_deletedAt (deleted_at), INDEX IDX_ublBusinessBranch_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublBusinessBranch_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublBusinessBranch_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublCountry (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublCountry_bolActive (bolActive), INDEX IDX_ublCountry_deletedAt (deleted_at), INDEX IDX_ublCountry_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublCountry_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublCountry_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublCurrency (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublCurrency_bolActive (bolActive), INDEX IDX_ublCurrency_deletedAt (deleted_at), INDEX IDX_ublCurrency_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublCurrency_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublCurrency_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublIndustry (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublIndustry_bolActive (bolActive), INDEX IDX_ublIndustry_deletedAt (deleted_at), INDEX IDX_ublIndustry_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublIndustry_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublIndustry_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublPriority (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, strDescription VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublPriority_bolActive (bolActive), INDEX IDX_ublPriority_deletedAt (deleted_at), INDEX IDX_ublPriority_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublPriority_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublPriority_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublProjectSaleType (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, intBusinessBranchId INT NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_7E750F0FC096CAA3 (intBusinessBranchId), INDEX IDX_ublProjectSaleType_bolActive (bolActive), INDEX IDX_ublProjectSaleType_deletedAt (deleted_at), INDEX IDX_ublProjectSaleType_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublProjectSaleType_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublProjectSaleType_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublStatus (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, strDescription VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublStatus_bolActive (bolActive), INDEX IDX_ublStatus_deletedAt (deleted_at), INDEX IDX_ublStatus_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublStatus_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublStatus_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');

        $this->addSql('CREATE TABLE ublTechnology (intId INT AUTO_INCREMENT NOT NULL, strFriendlyName VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, strHandle VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, intDisplayOrder INT DEFAULT NULL, dtmCreatedAt DATETIME NOT NULL, bolActive TINYINT(1) DEFAULT \'1\' NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ublTechnology_bolActive (bolActive), INDEX IDX_ublTechnology_deletedAt (deleted_at), INDEX IDX_ublTechnology_dtmCreatedAt (dtmCreatedAt), INDEX IDX_ublTechnology_intDisplayOrder (intDisplayOrder), UNIQUE INDEX UK_ublTechnology_strHandle (strHandle), PRIMARY KEY(intId)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
    }
}
